### PR TITLE
Run mypy without --no-strict-optional

### PR DESCRIPTION
**Pull request by jpopelka**
https://mypy.readthedocs.io/en/stable/kinds_of_types.html#no-strict-optional

### CODE REVIEW

**Comment by jpopelka** [comment]
recheck

**Comment by jpopelka** [comment]
> STEP 3/7: RUN set -ex;     mkdir -p ${HOME}/.config &&     echo "deployment: dev" > ${HOME}/.config/packit-service.yaml
> /bin/sh: error while loading shared libraries: libc.so.6: cannot change memory protections

what the hack???

**Comment by jpopelka** [comment]
recheck

**Comment by jpopelka** [comment]
> STEP 3/7: RUN set -ex;     mkdir -p ${HOME}/.config &&     echo "deployment: dev" > ${HOME}/.config/packit-service.yaml
> /bin/sh: error while loading shared libraries: libc.so.6: cannot change memory protections

From containers/podman#3234 & containers/podman#10817 it looks like a SELinux-related problem, but `podman system reset` doesn't help and I don't have permissions to disable SELinux.
I'll merge manually once approved and hope that it'll disappear as it appeared :-)

**Review by majamassarini — APPROVED** [review]
I played with it and locally I have no errors neither with the new pre-commit hook or the hardly tests.
I wish we were lucky!

But I think we will be not lucky. I opened the PR I am working on (even if it has just a no useful commit which is already inside this PR :-)) just to see if the zuul tests pass and they did not.

**Pull request merged**
